name: dart_participants_lottery
description: A simple command-line application.
version: 1.1.0
repository: https://github.com/areee/dart_participants_lottery

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
